### PR TITLE
fix metrics type metadata when some quantiles are cleaned due to summary window

### LINKED ISSUE #120: Delivering no logs for a while leads to `unsupported` metric type for quantile metrics, causing Prometheus scrapes to fail
### Describe the bug

VictoriaLogs provides `unsupported` as metric type for three metrics after a while when no logs are ingested, which causes Prometheus scrapes to fail.

```
# HELP vl_insert_flush_duration_seconds
# TYPE vl_insert_flush_duration_seconds unsupported
vl_insert_flush_duration_seconds_sum{type="opentelemetry_protobuf"} 3.2394530889999835
vl_insert_flush_duration_seconds_count{type="opentelemetry_protobuf"} 46379
# HELP vl_merge_bytes
# TYPE vl_merge_bytes unsupported
vl_merge_bytes_sum{type="storage/inmemory"} 100349433
vl_merge_bytes_count{type="storage/inmemory"} 3626
vl_merge_bytes_sum{type="storage/small"} 147157326
vl_merge_bytes_count{type="storage/small"} 4093
# HELP vl_merge_duration_seconds
# TYPE vl_merge_duration_seconds unsupported
vl_merge_duration_seconds_sum{type="storage/inmemory"} 9.134269375999992
vl_merge_duration_seconds_count{type="storage/inmemory"} 3626
vl_merge_duration_seconds_sum{type="storage/small"} 48.66305795399984
vl_merge_duration_seconds_count{type="storage/small"} 4093
```

Image

### To Reproduce

* Deliver logs via OpenTelemetry Collector to VictoriaLogs
* Stop delivering logs
* After a while (> 3.5 minutes in my tests), the type of the above metrics, which normally is reported as `summary`, flips to `unsupported`, and the `quantile` metrics disappear.

Example when OpenTelemetry Collectors are exporting correctly (same for the others):
```
# HELP vl_insert_flush_duration_seconds
# TYPE vl_insert_flush_duration_seconds summary
vl_insert_flush_duration_seconds{type="opentelemetry_protobuf",quantile="0.5"} 7.2204e-05
vl_insert_flush_duration_seconds{type="opentelemetry_protobuf",quantile="0.9"} 0.001110752
vl_insert_flush_duration_seconds{type="opentelemetry_protobuf",quantile="0.97"} 0.00232637
vl_insert_flush_duration_seconds{type="opentelemetry_protobuf",quantile="0.99"} 0.00658483
vl_insert_flush_duration_seconds{type="opentelemetry_protobuf",quantile="1"} 0.009116569
vl_insert_flush_duration_seconds_sum{type="opentelemetry_protobuf"} 3.3206566299999833
vl_insert_flush_duration_seconds_count{type="opentelemetry_protobuf"} 46570
```

### Version

victoria-logs-20260311-161844-tags-v1.48.0-0-g3b50299862

### Logs

Don't show anything interesting, the last `info` level entry was three days ago.

### Screenshots

_No response_

### Used command-line flags

-storageDataPath=/victorialogs-data
-retention.maxDiskSpaceUsageBytes=24GiB
-retentionPeriod=8w
-inmemoryDataFlushInterval=1m
-loggerFormat=json
-metrics.exposeMetadata=true
-flagsAuthKey=file:///credentials/flagsAuthKey
-forceFlushAuthKey=file:///credentials/forceFlushAuthKey
-forceMergeAuthKey=file:///credentials/forceMergeAuthKey
-logNewStreamsAuthKey=file:///credentials/logNewStreamsAuthKey
-partitionManageAuthKey=file:///credentials/partitionManageAuthKey
-pprofAuthKey=file:///credentials/pprofAuthKey

### Additional information

This VictoriaLogs installation runs as `StatefulSet` in a Kubernetes cluster. I can provide the `.yaml` files if needed.

### PR DESCRIPTION
**Pull request by jiekun**
fix https://github.com/VictoriaMetrics/metrics/issues/120

For summary data, it contains `*Summary` and multiple `*quantileValue`. When printing, they'll be sorted by their `metricType`:
1. `*Summary` has `unsupported`.
2. `*quantileValue` has `summary`.

So `*quantileValue` are always printed first.

However, the  `*quantileValue` could be removed if stale for 5 minutes, in this case, the `metricType` of `*Summary` will be printed (as `unsupported`), while the expectation would be `summary`.

This pull request specific the metric type for both to `summary` and sort them by `isAux`.

---
## Summary by cubic
Fixes TYPE metadata for summary metrics when quantiles expire. Always emits TYPE summary and sorts quantiles before _sum/_count using an auxiliary flag, not metric-type sorting.

- **Bug Fixes**
  - Set `Summary.metricType()` to return "summary" so metadata stays correct even if only _sum/_count remain.
  - Use `isAux` to sort quantiles before _sum/_count within the same family; remove metric-type-based sorting.
  - Add a unit test for a short-window `SummaryExt` to verify TYPE summary after quantiles expire; add an `isAux` comment to clarify the sorting behavior.

<sup>Written for commit ef2c19af469953d3206e066931a82da5c76f8466. Summary will update on new commits.</sup>

### CODE REVIEW

**Review by hagen1778 — COMMENTED** [review]
Thanks

**Review by hagen1778 — APPROVED** [review]

**Review by f41gh7 — APPROVED** [review]
LGTM

File: set_example_test.go [hunk 1]
```diff
@@ -54,6 +55,11 @@ func ExampleExposeMetadata() {
 	// This summary will have quantiles printed before _sum/_count metrics
 	s.NewSummary(`vm_request_duration_seconds{path="/api/v1/query_range"}`).Update(1)
 
+	var testSummaryQuantilesNoop = []float64{0.5, 0.9, 0.97, 0.99, 1}
+	testWindow := 50 * time.Millisecond
+	s.NewSummaryExt(`test_summary_expire_quick`, testWindow, testSummaryQuantilesNoop).Update(1)
+	time.Sleep(4 * testWindow)
```
Comment (f41gh7) [inline set_example_test.go]: Lets move this test into `set_test`.

Comment (jiekun) [reply set_example_test.go]: done, thank you!

File: set_example_test.go [hunk 2]
```diff
@@ -54,6 +55,11 @@ func ExampleExposeMetadata() {
 	// This summary will have quantiles printed before _sum/_count metrics
 	s.NewSummary(`vm_request_duration_seconds{path="/api/v1/query_range"}`).Update(1)
 
+	var testSummaryQuantilesNoop = []float64{0.5, 0.9, 0.97, 0.99, 1}
```
[the remark this answers is not in the document]
Comment (jiekun) [reply set_example_test.go]: moved to `set_test.go`

**Comment by hagen1778** [comment]
Thanks!

**Comment by hagen1778** [comment]
This change was included into https://github.com/VictoriaMetrics/metrics/releases/tag/v1.43.1
@jiekun pls take care of making corresponding update PRs to depending repos.

**Comment by makasim** [comment]
The fix is available in VictoriaMetrics since v1.140.0, v1.136.4, and v1.122.19.
